# Generated by Django 5.2.8 on 2025-12-20 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations were manually copied here
# and the RunPython operation was updated to reference local versions:
#   - core.migrations.0006_migrate_existing_data_to_grupos

def migrate_data_to_grupos(apps, schema_editor):
    """
    Migra los datos existentes al nuevo sistema de grupos.
    Crea un grupo "Grupo General" para cada docente y asigna todas sus
    invitaciones y referrals.
    """
    Grupo = apps.get_model('core', 'Grupo')
    Invitation = apps.get_model('core', 'Invitation')
    Referral = apps.get_model('core', 'Referral')
    User = apps.get_model('auth', 'User')

    docente_ids = set()

    for inv in Invitation.objects.select_related('creator').all():
        if inv.creator:
            docente_ids.add(inv.creator.id)

    for ref in Referral.objects.select_related('docente').all():
        if ref.docente:
            docente_ids.add(ref.docente.id)

    docente_grupo_map = {}
    for docente_id in docente_ids:
        docente = User.objects.get(id=docente_id)
        grupo = Grupo.objects.create(
            nombre='Grupo General',
            descripcion='Grupo creado automáticamente durante la migración del sistema',
            docente=docente,
            active=True,
        )
        docente_grupo_map[docente_id] = grupo

    for inv in Invitation.objects.select_related('creator').all():
        if inv.creator and inv.creator.id in docente_grupo_map:
            inv.grupo = docente_grupo_map[inv.creator.id]
            inv.save()

    for ref in Referral.objects.select_related('docente').all():
        if ref.docente and ref.docente.id in docente_grupo_map:
            ref.grupo = docente_grupo_map[ref.docente.id]
            ref.save()


def reverse_migration(apps, schema_editor):
    """
    Revierte la migración eliminando la asignación de grupos.
    """
    Invitation = apps.get_model('core', 'Invitation')
    Referral = apps.get_model('core', 'Referral')

    Invitation.objects.all().update(grupo=None)
    Referral.objects.all().update(grupo=None)

class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_invitation_referral'), ('core', '0003_notification'), ('core', '0004_alter_notification_options_and_more'), ('core', '0005_grupo_invitation_grupo_referral_grupo_and_more'), ('core', '0006_migrate_existing_data_to_grupos')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('docente', 'Docente'), ('estudiante', 'Estudiante')], default='estudiante', max_length=10)),
                ('esta_activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'core_userprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL, db_constraint=False)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100)),
                ('unread', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_notifications', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_notifications', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('comment_section', models.CharField(blank=True, max_length=2, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to=settings.AUTH_USER_MODEL, db_constraint=False)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('uses_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.grupo')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_students', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.invitation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.grupo')),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'unique_together': {('student', 'grupo')},
            },
        ),
        migrations.RunPython(
            code=migrate_data_to_grupos,
            reverse_code=reverse_migration,
        ),
    ]
