# Generated by Django 5.2.8 on 2025-11-23 00:13

from django.db import migrations


def migrate_data_to_grupos(apps, schema_editor):
    """
    Migra los datos existentes al nuevo sistema de grupos.
    Crea un grupo "Grupo General" para cada docente y asigna todas sus invitaciones y referrals.
    """
    Grupo = apps.get_model('core', 'Grupo')
    Invitation = apps.get_model('core', 'Invitation')
    Referral = apps.get_model('core', 'Referral')
    User = apps.get_model('auth', 'User')
    
    # Obtener todos los docentes que tienen invitaciones o referrals
    docente_ids = set()
    
    # Docentes con invitaciones (el campo es 'creator')
    for inv in Invitation.objects.select_related('creator').all():
        if inv.creator:
            docente_ids.add(inv.creator.id)
    
    # Docentes con referrals
    for ref in Referral.objects.select_related('docente').all():
        if ref.docente:
            docente_ids.add(ref.docente.id)
    
    # Crear un grupo "Grupo General" para cada docente
    docente_grupo_map = {}
    for docente_id in docente_ids:
        docente = User.objects.get(id=docente_id)
        grupo = Grupo.objects.create(
            nombre='Grupo General',
            descripcion='Grupo creado automáticamente durante la migración del sistema',
            docente=docente,
            active=True
        )
        docente_grupo_map[docente_id] = grupo
    
    # Asignar todas las invitaciones a sus respectivos grupos
    for inv in Invitation.objects.select_related('creator').all():
        if inv.creator and inv.creator.id in docente_grupo_map:
            inv.grupo = docente_grupo_map[inv.creator.id]
            inv.save()
    
    # Asignar todos los referrals a sus respectivos grupos
    for ref in Referral.objects.select_related('docente').all():
        if ref.docente and ref.docente.id in docente_grupo_map:
            ref.grupo = docente_grupo_map[ref.docente.id]
            ref.save()


def reverse_migration(apps, schema_editor):
    """
    Revierte la migración eliminando la asignación de grupos.
    """
    Invitation = apps.get_model('core', 'Invitation')
    Referral = apps.get_model('core', 'Referral')
    
    # Eliminar la asignación de grupos
    Invitation.objects.all().update(grupo=None)
    Referral.objects.all().update(grupo=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_grupo_invitation_grupo_referral_grupo_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data_to_grupos, reverse_migration),
    ]
