# Generated by Django 5.2.8 on 2026-01-06

from django.conf import settings
from django.db import migrations, models


def create_userprofile_if_missing(apps, schema_editor):
    """
    Create core_userprofile table if it doesn't exist, with proper schema.
    Works for both SQLite and MySQL/MariaDB.
    """
    connection = schema_editor.connection
    introspection = connection.introspection
    existing_tables = set(introspection.table_names())

    if "core_userprofile" in existing_tables:
        return

    # Create table using raw SQL so column types exactly match `auth_user.id` (bigint).
    # This avoids FK type mismatch issues when creating the table dynamically.
    create_sql = """
        CREATE TABLE IF NOT EXISTS `core_userprofile` (
            `id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY,
            `user_id` bigint NOT NULL UNIQUE,
            `rol` varchar(10) NOT NULL,
            `esta_activo` tinyint(1) NOT NULL,
            CONSTRAINT `core_userprofile_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
    """
    schema_editor.execute(create_sql)


def drop_userprofile_if_created(apps, schema_editor):
    connection = schema_editor.connection
    introspection = connection.introspection
    existing_tables = set(introspection.table_names())
    if "core_userprofile" in existing_tables:
        schema_editor.execute("DROP TABLE IF EXISTS `core_userprofile`")


class Migration(migrations.Migration):
    # Esta migración ejecuta DDL directamente (schema_editor.create_model)
    # MySQL/MariaDB no permiten ejecutar ciertas instrucciones DDL dentro
    # de una transacción que no puede revertirse, así que desactivamos
    # la envoltura transaccional para esta migración.
    atomic = False
    dependencies = [
        ("core", "0001_squashed_0006_migrate_existing_data_to_grupos"),
    ]

    operations = [
        migrations.RunPython(create_userprofile_if_missing, drop_userprofile_if_created),
    ]
