# Generated by Django 5.2.8 on 2026-01-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True, 'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
    ]
