# Generated by Django 5.2.8 on 2026-01-07 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_userprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # The `user_id` column already exists in the database (created by a prior
        # SQL migration). We only need to update Django's migration state so the
        # ORM knows about the `user` OneToOneField. Use SeparateDatabaseAndState
        # to add the field to state without performing a database operation.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='user',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, db_constraint=False),
                ),
            ],
        ),
    ]
