# Generated by Django 5.2.8 on 2025-12-20 03:30

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


# Functions from the following migrations were manually copied here
# and the RunPython operations updated to reference these local versions.
# Originally:
#   - contabilidad.migrations.0010_fix_invalid_transactions.fix_transactions_with_both_positive
#   - contabilidad.migrations.0016_convert_int_pk_to_bigint.convert_int_pk_fk_to_bigint

def fix_transactions_with_both_positive(apps, schema_editor):
    """
    Corrige transacciones que tienen tanto debe como haber > 0.

    Divide la transacción en dos líneas (una en debe y otra en haber)
    y elimina la línea inválida original. Segura de re-ejecutar.
    """
    try:
        EmpresaTransaccion = apps.get_model('contabilidad', 'EmpresaTransaccion')
    except LookupError:
        return

    violaciones = EmpresaTransaccion.objects.filter(debe__gt=0, haber__gt=0)
    for transaccion in violaciones:
        EmpresaTransaccion.objects.create(
            asiento=transaccion.asiento,
            cuenta=transaccion.cuenta,
            detalle_linea=f"{transaccion.detalle_linea or ''} (Debe - corregido)",
            debe=transaccion.debe,
            haber=0,
        )
        EmpresaTransaccion.objects.create(
            asiento=transaccion.asiento,
            cuenta=transaccion.cuenta,
            detalle_linea=f"{transaccion.detalle_linea or ''} (Haber - corregido)",
            debe=0,
            haber=transaccion.haber,
        )
        transaccion.delete()


def convert_int_pk_fk_to_bigint(apps, schema_editor):
    """
    Convierte todas las PK `id` INT y sus FKs referenciadas a BIGINT,
    preservando reglas ON DELETE/UPDATE y nulabilidad de columnas.
    Segura de re-ejecutar: si ya es BIGINT se omite.
    """
    with connection.cursor() as cursor:
        cursor.execute("SELECT DATABASE()")
        schema = cursor.fetchone()[0]

        cursor.execute(
            """
            SELECT TABLE_NAME
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = %s
              AND COLUMN_NAME = 'id'
              AND DATA_TYPE = 'int'
            """,
            [schema],
        )
        int_pk_tables = [row[0] for row in cursor.fetchall()]
        if not int_pk_tables:
            return

        for table in int_pk_tables:
            cursor.execute(
                """
                SELECT kcu.TABLE_NAME AS child_table,
                       kcu.CONSTRAINT_NAME,
                       kcu.COLUMN_NAME,
                       rc.DELETE_RULE,
                       rc.UPDATE_RULE
                FROM information_schema.KEY_COLUMN_USAGE kcu
                JOIN information_schema.REFERENTIAL_CONSTRAINTS rc
                  ON rc.CONSTRAINT_SCHEMA = kcu.CONSTRAINT_SCHEMA
                 AND rc.CONSTRAINT_NAME   = kcu.CONSTRAINT_NAME
                WHERE kcu.TABLE_SCHEMA = %s
                  AND kcu.REFERENCED_TABLE_NAME = %s
                  AND kcu.REFERENCED_COLUMN_NAME = 'id'
                ORDER BY kcu.TABLE_NAME, kcu.CONSTRAINT_NAME
                """,
                [schema, table],
            )
            fks = cursor.fetchall()

            for child_table, constraint_name, column_name, delete_rule, update_rule in fks:
                cursor.execute(
                    f"ALTER TABLE `{child_table}` DROP FOREIGN KEY `{constraint_name}`"
                )

            cursor.execute(
                f"ALTER TABLE `{table}` MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT"
            )

            for child_table, constraint_name, column_name, delete_rule, update_rule in fks:
                cursor.execute(
                    """
                    SELECT IS_NULLABLE
                    FROM information_schema.COLUMNS
                    WHERE TABLE_SCHEMA = %s
                      AND TABLE_NAME = %s
                      AND COLUMN_NAME = %s
                    """,
                    [schema, child_table, column_name],
                )
                nullable = cursor.fetchone()[0]
                null_sql = "NULL" if nullable == "YES" else "NOT NULL"

                cursor.execute(
                    f"ALTER TABLE `{child_table}` MODIFY COLUMN `{column_name}` BIGINT {null_sql}"
                )

                delete_sql = f" ON DELETE {delete_rule}" if delete_rule else ""
                update_sql = f" ON UPDATE {update_rule}" if update_rule else ""

                cursor.execute(
                    f"ALTER TABLE `{child_table}`\n"
                    f"  ADD CONSTRAINT `{constraint_name}`\n"
                    f"  FOREIGN KEY (`{column_name}`) REFERENCES `{table}`(`id`){delete_sql}{update_sql}"
                )

class Migration(migrations.Migration):

    replaces = [('contabilidad', '0001_initial'), ('contabilidad', '0002_empresa_visible_to_supervisor'), ('contabilidad', '0003_empresacomment'), ('contabilidad', '0004_alter_empresaasiento_options_and_more'), ('contabilidad', '0005_empresaasiento_anulado'), ('contabilidad', '0006_alter_empresacomment_section'), ('contabilidad', '0007_remove_empresatransaccion_parcial_and_more'), ('contabilidad', '0008_add_check_constraints'), ('contabilidad', '0009_alter_asiento_options_alter_plandecuentas_options_and_more'), ('contabilidad', '0010_fix_invalid_transactions'), ('contabilidad', '0011_add_performance_indexes'), ('contabilidad', '0012_empresatercero_delete_asiento_delete_transaccion_and_more'), ('contabilidad', '0013_empresatercero_delete_asiento_delete_transaccion_and_more'), ('contabilidad', '0014_empresatercero_delete_asiento_delete_transaccion_and_more'), ('contabilidad', '0015_empresatercero_delete_asiento_delete_transaccion_and_more'), ('contabilidad', '0016_convert_int_pk_to_bigint')]

    initial = True

    dependencies = [
        ('core', '0006_migrate_existing_data_to_grupos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion_general', models.TextField()),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Confirmado', 'Confirmado')], default='Borrador', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'db_table': 'contabilidad_asiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanDeCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Patrimonio', 'Patrimonio'), ('Ingreso', 'Ingreso'), ('Costo', 'Costo'), ('Gasto', 'Gasto')], max_length=10)),
                ('naturaleza', models.CharField(choices=[('Deudora', 'Deudora'), ('Acreedora', 'Acreedora')], max_length=9)),
                ('estado_situacion', models.BooleanField(db_comment='True si es cuenta de Balance, False si es de Resultado')),
                ('es_auxiliar', models.BooleanField(db_comment='True si es una cuenta hoja (auxiliar) que puede recibir transacciones', default=False)),
            ],
            options={
                'verbose_name': 'Plan de Cuenta',
                'verbose_name_plural': 'Planes de Cuentas',
                'db_table': 'contabilidad_plandecuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_linea', models.CharField(blank=True, max_length=500, null=True)),
                ('parcial', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'contabilidad_transaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=False)),
                ('join_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='contabilidad.empresa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
                ('visible_to_supervisor', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'contabilidad_empresa',
            },
        ),
        migrations.CreateModel(
            name='EmpresaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('descripcion_general', models.TextField()),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Confirmado', 'Confirmado'), ('Anulado', 'Anulado')], db_index=True, default='Borrador', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='contabilidad.empresa')),
                ('anulado_mediante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anula_a', to='contabilidad.empresaasiento')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_anulados', to=settings.AUTH_USER_MODEL)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('numero_asiento', models.PositiveIntegerField(default=1, editable=False, help_text='Número secuencial del asiento por empresa (auditoría)')),
            ],
            options={
                'verbose_name': 'Asiento (Empresa)',
                'verbose_name_plural': 'Asientos (Empresa)',
                'db_table': 'contabilidad_empresa_asiento',
                'ordering': ['empresa', '-fecha', '-numero_asiento'],
                'unique_together': {('empresa', 'numero_asiento')},
            },
        ),
        migrations.CreateModel(
            name='EmpresaPlanCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Patrimonio', 'Patrimonio'), ('Ingreso', 'Ingreso'), ('Costo', 'Costo'), ('Gasto', 'Gasto')], db_index=True, max_length=10)),
                ('naturaleza', models.CharField(choices=[('Deudora', 'Deudora'), ('Acreedora', 'Acreedora')], max_length=9)),
                ('estado_situacion', models.BooleanField(help_text='True si es cuenta de Balance, False si es de Resultado')),
                ('es_auxiliar', models.BooleanField(default=False, help_text='True si es una cuenta hoja (auxiliar) que puede recibir transacciones')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='contabilidad.empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='contabilidad.empresaplancuenta')),
            ],
            options={
                'verbose_name': 'Cuenta (Empresa)',
                'verbose_name_plural': 'Cuentas (Empresas)',
                'db_table': 'contabilidad_empresa_plandecuentas',
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='EmpresaTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_linea', models.CharField(blank=True, max_length=500, null=True)),
                ('parcial', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.empresaasiento')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.empresaplancuenta')),
            ],
            options={
                'verbose_name': 'Transacción (Empresa)',
                'verbose_name_plural': 'Transacciones (Empresa)',
                'db_table': 'contabilidad_empresa_transaccion',
            },
        ),
        migrations.CreateModel(
            name='EmpresaSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisiones', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisores', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Empresa Supervisor',
                'verbose_name_plural': 'Empresa Supervisores',
                'db_table': 'contabilidad_empresa_supervisor',
                'unique_together': {('empresa', 'docente')},
            },
        ),
        migrations.CreateModel(
            name='EmpresaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('PL', 'Plan de Cuentas'), ('DI', 'Libro Diario'), ('RP', 'Reportes')], max_length=2)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Comentario (Empresa)',
                'verbose_name_plural': 'Comentarios (Empresas)',
                'db_table': 'contabilidad_empresa_comment',
            },
        ),
        migrations.AddIndex(
            model_name='empresaasiento',
            index=models.Index(fields=['empresa', 'fecha'], name='contabilida_empresa_e7b4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaasiento',
            index=models.Index(fields=['empresa', 'estado'], name='contabilida_empresa_b0d426_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaasiento',
            index=models.Index(fields=['empresa', 'numero_asiento'], name='contabilida_empresa_c4883a_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaplancuenta',
            index=models.Index(fields=['empresa', 'codigo'], name='contabilida_empresa_d931fd_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaplancuenta',
            index=models.Index(fields=['empresa', 'tipo'], name='contabilida_empresa_75cc60_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaplancuenta',
            index=models.Index(fields=['empresa', 'es_auxiliar'], name='contabilida_empresa_bc85eb_idx'),
        ),
        migrations.AddIndex(
            model_name='empresatransaccion',
            index=models.Index(fields=['asiento', 'cuenta'], name='contabilida_asiento_6afe9f_idx'),
        ),
        migrations.AddIndex(
            model_name='empresatransaccion',
            index=models.Index(fields=['cuenta'], name='contabilida_cuenta__c04094_idx'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE contabilidad_empresa_asiento ADD COLUMN IF NOT EXISTS anulado TINYINT(1) DEFAULT 0 NOT NULL;',
                    reverse_sql='ALTER TABLE contabilidad_empresa_asiento DROP COLUMN IF EXISTS anulado;',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='empresaasiento',
                    name='anulado',
                    field=models.BooleanField(db_index=True, default=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='empresacomment',
            name='section',
            field=models.CharField(choices=[('PL', 'Plan de Cuentas'), ('DI', 'Libro Diario'), ('MA', 'Libro Mayor'), ('RP', 'Reportes')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='empresatransaccion',
            name='parcial',
        ),
        migrations.AddField(
            model_name='empresaplancuenta',
            name='activa',
            field=models.BooleanField(default=True, help_text='True si la cuenta está activa y puede recibir transacciones'),
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField(help_text='Mes del 1-12, o 0 para indicar cierre anual')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('BLOQUEADO', 'Bloqueado (Auditoría)')], default='ABIERTO', max_length=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones del cierre')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_cerrados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Periodo Contable',
                'verbose_name_plural': 'Periodos Contables',
                'db_table': 'contabilidad_periodo',
                'ordering': ['-anio', '-mes'],
                'indexes': [models.Index(fields=['empresa', 'anio', 'mes'], name='contabilida_empresa_0d20af_idx'), models.Index(fields=['empresa', 'estado'], name='contabilida_empresa_5813d1_idx')],
                'unique_together': {('empresa', 'anio', 'mes')},
            },
        ),
        migrations.RunSQL(
            sql='\n                ALTER TABLE contabilidad_empresa_transaccion\n                ADD CONSTRAINT chk_debe_positivo \n                    CHECK (debe >= 0);\n            ',
            reverse_sql='\n                ALTER TABLE contabilidad_empresa_transaccion\n                DROP CONSTRAINT IF EXISTS chk_debe_positivo;\n            ',
            hints={'mysql': True},
        ),
        migrations.RunSQL(
            sql='\n                ALTER TABLE contabilidad_empresa_transaccion\n                ADD CONSTRAINT chk_haber_positivo \n                    CHECK (haber >= 0);\n            ',
            reverse_sql='\n                ALTER TABLE contabilidad_empresa_transaccion\n                DROP CONSTRAINT IF EXISTS chk_haber_positivo;\n            ',
            hints={'mysql': True},
        ),
        migrations.RunSQL(
            sql='\n                ALTER TABLE contabilidad_empresa_transaccion\n                ADD CONSTRAINT chk_no_ambos_positivos \n                    CHECK (NOT (debe > 0 AND haber > 0));\n            ',
            reverse_sql='\n                ALTER TABLE contabilidad_empresa_transaccion\n                DROP CONSTRAINT IF EXISTS chk_no_ambos_positivos;\n            ',
            hints={'mysql': True},
        ),
        migrations.RunSQL(
            sql='\n                ALTER TABLE contabilidad_empresa_transaccion\n                ADD CONSTRAINT chk_al_menos_uno_positivo \n                    CHECK (debe > 0 OR haber > 0);\n            ',
            reverse_sql='\n                ALTER TABLE contabilidad_empresa_transaccion\n                DROP CONSTRAINT IF EXISTS chk_al_menos_uno_positivo;\n            ',
            hints={'mysql': True},
        ),
        migrations.AlterModelOptions(
            name='asiento',
            options={'managed': True, 'verbose_name': 'Asiento Contable', 'verbose_name_plural': 'Asientos Contables'},
        ),
        migrations.AlterModelOptions(
            name='plandecuentas',
            options={'managed': True, 'verbose_name': 'Plan de Cuenta', 'verbose_name_plural': 'Planes de Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'managed': True, 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.RunPython(
            code=fix_transactions_with_both_positive,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunSQL(
            sql='\n            CREATE INDEX IF NOT EXISTS idx_empresa_transaccion_cta_fecha \n            ON contabilidad_empresa_transaccion (cuenta_id, asiento_id);\n            ',
            reverse_sql='\n            DROP INDEX IF EXISTS idx_empresa_transaccion_cta_fecha \n            ON contabilidad_empresa_transaccion;\n            ',
        ),
        migrations.RunSQL(
            sql='\n            CREATE INDEX IF NOT EXISTS idx_empresa_asiento_empresa_fecha \n            ON contabilidad_empresa_asiento (empresa_id, fecha);\n            ',
            reverse_sql='\n            DROP INDEX IF EXISTS idx_empresa_asiento_empresa_fecha \n            ON contabilidad_empresa_asiento;\n            ',
        ),
        migrations.RunSQL(
            sql='\n            CREATE INDEX IF NOT EXISTS idx_empresa_asiento_anulado \n            ON contabilidad_empresa_asiento (anulado);\n            ',
            reverse_sql='\n            DROP INDEX IF EXISTS idx_empresa_asiento_anulado \n            ON contabilidad_empresa_asiento;\n            ',
        ),
        migrations.RunSQL(
            sql='\n            CREATE INDEX IF NOT EXISTS idx_empresa_plancuenta_empresa \n            ON contabilidad_empresa_plandecuentas (empresa_id, codigo);\n            ',
            reverse_sql='\n            DROP INDEX IF EXISTS idx_empresa_plancuenta_empresa \n            ON contabilidad_empresa_plandecuentas;\n            ',
        ),
        migrations.RunSQL(
            sql='SELECT 1',
            reverse_sql='SELECT 1',
        ),
        migrations.RunSQL(
            sql='SELECT 1',
            reverse_sql='SELECT 1',
        ),
        migrations.RunSQL(
            sql='\n                ALTER TABLE contabilidad_empresa_transaccion\n                  ADD COLUMN IF NOT EXISTS tercero_id bigint NULL;\n                ALTER TABLE contabilidad_empresa_transaccion\n                  DROP FOREIGN KEY IF EXISTS contabilidad_empr_trans_tercero_fk;\n                ALTER TABLE contabilidad_empresa_transaccion\n                  ADD CONSTRAINT contabilidad_empr_trans_tercero_fk\n                  FOREIGN KEY (tercero_id) REFERENCES contabilidad_empresa_tercero(id)\n                  ON DELETE SET NULL;\n                ALTER TABLE contabilidad_empresa_transaccion\n                  ADD INDEX IF NOT EXISTS contab_empresatransaccion_tercero_idx (tercero_id);\n            ',
            reverse_sql='\n                ALTER TABLE contabilidad_empresa_transaccion\n                  DROP FOREIGN KEY IF EXISTS contabilidad_empr_trans_tercero_fk;\n                ALTER TABLE contabilidad_empresa_transaccion\n                  DROP COLUMN IF EXISTS tercero_id;\n            ',
        ),
        migrations.CreateModel(
            name='EmpresaTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(help_text='RUC, Cédula, DNI u otro identificador fiscal', max_length=20)),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('EMPLEADO', 'Empleado'), ('ACCIONISTA', 'Accionista'), ('GOBIERNO', 'Gobierno'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terceros_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceros', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Tercero (Empresa)',
                'verbose_name_plural': 'Terceros (Empresas)',
                'db_table': 'contabilidad_empresa_tercero',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Asiento',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='ip_address_anulacion',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde la que se anuló el asiento', null=True),
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='ip_address_creacion',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde la que se creó el asiento', null=True),
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='ip_address_modificacion',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde la que se modificó el asiento', null=True),
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresatransaccion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresatransaccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plandecuentas',
            name='padre',
            field=models.ForeignKey(blank=True, db_comment='Clave foránea recursiva para la estructura de árbol', null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.plandecuentas'),
        ),
        migrations.AlterField(
            model_name='empresaasiento',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresatransaccion',
            name='tercero',
            field=models.ForeignKey(blank=True, help_text='Cliente, Proveedor, Empleado, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='contabilidad.empresatercero'),
        ),
        migrations.AddIndex(
            model_name='empresatercero',
            index=models.Index(fields=['empresa', 'tipo'], name='contabilida_empresa_f0fa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='empresatercero',
            index=models.Index(fields=['empresa', 'activo'], name='contabilida_empresa_ff4cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='empresatercero',
            index=models.Index(fields=['numero_identificacion'], name='contabilida_numero__9a26a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empresatercero',
            unique_together={('empresa', 'numero_identificacion')},
        ),
        migrations.RunPython(
            code=convert_int_pk_fk_to_bigint,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
    ]
