# Generated by Django 5.2.8 on 2025-11-20 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion_general', models.TextField()),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Confirmado', 'Confirmado')], default='Borrador', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'db_table': 'contabilidad_asiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanDeCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Patrimonio', 'Patrimonio'), ('Ingreso', 'Ingreso'), ('Costo', 'Costo'), ('Gasto', 'Gasto')], max_length=10)),
                ('naturaleza', models.CharField(choices=[('Deudora', 'Deudora'), ('Acreedora', 'Acreedora')], max_length=9)),
                ('estado_situacion', models.BooleanField(db_comment='True si es cuenta de Balance, False si es de Resultado')),
                ('es_auxiliar', models.BooleanField(db_comment='True si es una cuenta hoja (auxiliar) que puede recibir transacciones', default=False)),
            ],
            options={
                'verbose_name': 'Plan de Cuenta',
                'verbose_name_plural': 'Planes de Cuentas',
                'db_table': 'contabilidad_plandecuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_linea', models.CharField(blank=True, max_length=500, null=True)),
                ('parcial', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'contabilidad_transaccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('is_template', models.BooleanField(default=False)),
                ('join_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='contabilidad.empresa')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL, db_constraint=False)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'contabilidad_empresa',
            },
        ),
        migrations.CreateModel(
            name='EmpresaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion_general', models.TextField()),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Confirmado', 'Confirmado')], default='Borrador', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Asiento (Empresa)',
                'verbose_name_plural': 'Asientos (Empresa)',
                'db_table': 'contabilidad_empresa_asiento',
            },
        ),
        migrations.CreateModel(
            name='EmpresaPlanCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Patrimonio', 'Patrimonio'), ('Ingreso', 'Ingreso'), ('Costo', 'Costo'), ('Gasto', 'Gasto')], max_length=10)),
                ('naturaleza', models.CharField(choices=[('Deudora', 'Deudora'), ('Acreedora', 'Acreedora')], max_length=9)),
                ('estado_situacion', models.BooleanField()),
                ('es_auxiliar', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='contabilidad.empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.empresaplancuenta')),
            ],
            options={
                'verbose_name': 'Cuenta (Empresa)',
                'verbose_name_plural': 'Cuentas (Empresas)',
                'db_table': 'contabilidad_empresa_plandecuentas',
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='EmpresaTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_linea', models.CharField(blank=True, max_length=500, null=True)),
                ('parcial', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.empresaasiento')),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.empresaplancuenta')),
            ],
            options={
                'verbose_name': 'Transacción (Empresa)',
                'verbose_name_plural': 'Transacciones (Empresa)',
                'db_table': 'contabilidad_empresa_transaccion',
            },
        ),
        migrations.CreateModel(
            name='EmpresaSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisiones', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisores', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Empresa Supervisor',
                'verbose_name_plural': 'Empresa Supervisores',
                'db_table': 'contabilidad_empresa_supervisor',
                'unique_together': {('empresa', 'docente')},
            },
        ),
    ]
