# Generated by Django 5.2.8 on 2025-11-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='visible_to_supervisor',
            field=models.BooleanField(default=True),
        ),
    ]
