# Generated by Django 5.2.8 on 2025-11-20 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_empresa_visible_to_supervisor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('PL', 'Plan de Cuentas'), ('DI', 'Libro Diario'), ('RP', 'Reportes')], max_length=2)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Comentario (Empresa)',
                'verbose_name_plural': 'Comentarios (Empresas)',
                'db_table': 'contabilidad_empresa_comment',
            },
        ),
    ]
