# Generated by Django 5.2.8 on 2025-11-23 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_empresacomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresaasiento',
            options={'ordering': ['empresa', '-fecha', '-numero_asiento'], 'verbose_name': 'Asiento (Empresa)', 'verbose_name_plural': 'Asientos (Empresa)'},
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='anulado_mediante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anula_a', to='contabilidad.empresaasiento'),
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_anulados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='numero_asiento',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Número secuencial del asiento por empresa (auditoría)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresaasiento',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Confirmado', 'Confirmado'), ('Anulado', 'Anulado')], db_index=True, default='Borrador', max_length=10),
        ),
        migrations.AlterField(
            model_name='empresaasiento',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='empresaplancuenta',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='empresaplancuenta',
            name='es_auxiliar',
            field=models.BooleanField(default=False, help_text='True si es una cuenta hoja (auxiliar) que puede recibir transacciones'),
        ),
        migrations.AlterField(
            model_name='empresaplancuenta',
            name='estado_situacion',
            field=models.BooleanField(help_text='True si es cuenta de Balance, False si es de Resultado'),
        ),
        migrations.AlterField(
            model_name='empresaplancuenta',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='contabilidad.empresaplancuenta'),
        ),
        migrations.AlterField(
            model_name='empresaplancuenta',
            name='tipo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Patrimonio', 'Patrimonio'), ('Ingreso', 'Ingreso'), ('Costo', 'Costo'), ('Gasto', 'Gasto')], db_index=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='empresaasiento',
            unique_together={('empresa', 'numero_asiento')},
        ),
        migrations.AddIndex(
            model_name='empresaasiento',
            index=models.Index(fields=['empresa', 'fecha'], name='contabilida_empresa_e7b4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaasiento',
            index=models.Index(fields=['empresa', 'estado'], name='contabilida_empresa_b0d426_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaasiento',
            index=models.Index(fields=['empresa', 'numero_asiento'], name='contabilida_empresa_c4883a_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaplancuenta',
            index=models.Index(fields=['empresa', 'codigo'], name='contabilida_empresa_d931fd_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaplancuenta',
            index=models.Index(fields=['empresa', 'tipo'], name='contabilida_empresa_75cc60_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaplancuenta',
            index=models.Index(fields=['empresa', 'es_auxiliar'], name='contabilida_empresa_bc85eb_idx'),
        ),
        migrations.AddIndex(
            model_name='empresatransaccion',
            index=models.Index(fields=['asiento', 'cuenta'], name='contabilida_asiento_6afe9f_idx'),
        ),
        migrations.AddIndex(
            model_name='empresatransaccion',
            index=models.Index(fields=['cuenta'], name='contabilida_cuenta__c04094_idx'),
        ),
    ]
