# Generated by Django 5.2.8 on 2025-11-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_alter_empresaasiento_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Columna ya existe en la BD legacy
            state_operations=[
                migrations.AddField(
                    model_name='empresaasiento',
                    name='anulado',
                    field=models.BooleanField(db_index=True, default=False),
                )
            ]
        )
    ]
