# Generated by Django 5.2.8 on 2025-11-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_empresaasiento_anulado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresacomment',
            name='section',
            field=models.CharField(choices=[('PL', 'Plan de Cuentas'), ('DI', 'Libro Diario'), ('MA', 'Libro Mayor'), ('RP', 'Reportes')], max_length=2),
        ),
    ]
