# Generated by Django 5.2.8 on 2025-12-14 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_empresacomment_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresatransaccion',
            name='parcial',
        ),
        migrations.AddField(
            model_name='empresaplancuenta',
            name='activa',
            field=models.BooleanField(default=True, help_text='True si la cuenta está activa y puede recibir transacciones'),
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField(help_text='Mes del 1-12, o 0 para indicar cierre anual')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('BLOQUEADO', 'Bloqueado (Auditoría)')], default='ABIERTO', max_length=10)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Observaciones del cierre')),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_cerrados', to=settings.AUTH_USER_MODEL, db_constraint=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Periodo Contable',
                'verbose_name_plural': 'Periodos Contables',
                'db_table': 'contabilidad_periodo',
                'ordering': ['-anio', '-mes'],
                'indexes': [models.Index(fields=['empresa', 'anio', 'mes'], name='contabilida_empresa_0d20af_idx'), models.Index(fields=['empresa', 'estado'], name='contabilida_empresa_5813d1_idx')],
                'unique_together': {('empresa', 'anio', 'mes')},
            },
        ),
    ]
