# Generated by Django 5.2.8 on 2025-12-14 17:57

from django.db import migrations
import os
from django.conf import settings


class Migration(migrations.Migration):
    """
    Migración para agregar CHECK constraints a nivel de base de datos.
    
    Estos constraints garantizan integridad de datos incluso si se insertan
    registros por fuera de Django (SQL directo, otros sistemas, etc.).
    
    Cumple con CONTABILIDAD_BEST_PRACTICES.md sección 2.6
    """

    dependencies = [
        ('contabilidad', '0007_remove_empresatransaccion_parcial_and_more'),
    ]

    def _is_mysql(schema_editor):
        return schema_editor.connection.vendor == 'mysql'

    # Si estamos ejecutando tests con SQLite, omitimos estas operaciones
    if os.getenv('USE_SQLITE_FOR_TESTS', '0') == '1':
        operations = []
    else:
        operations = [
        # Nota: se omite bloque SET/prepare por incompatibilidad con SQLite en tests
        
        # CHECK constraints para EmpresaTransaccion
        migrations.RunSQL(
            sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                ADD CONSTRAINT chk_debe_positivo 
                    CHECK (debe >= 0);
            """,
            reverse_sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                DROP CONSTRAINT IF EXISTS chk_debe_positivo;
            """,
            state_operations=[],
            hints={'mysql': True}
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                ADD CONSTRAINT chk_haber_positivo 
                    CHECK (haber >= 0);
            """,
            reverse_sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                DROP CONSTRAINT IF EXISTS chk_haber_positivo;
            """,
            state_operations=[],
            hints={'mysql': True}
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                ADD CONSTRAINT chk_no_ambos_positivos 
                    CHECK (NOT (debe > 0 AND haber > 0));
            """,
            reverse_sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                DROP CONSTRAINT IF EXISTS chk_no_ambos_positivos;
            """,
            state_operations=[],
            hints={'mysql': True}
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                ADD CONSTRAINT chk_al_menos_uno_positivo 
                    CHECK (debe > 0 OR haber > 0);
            """,
            reverse_sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                DROP CONSTRAINT IF EXISTS chk_al_menos_uno_positivo;
            """,
            state_operations=[],
            hints={'mysql': True}
        ),
        
        # NOTA: No agregar constraints para contabilidad_transaccion 
        # ya que el modelo fue removido en 0007_remove_empresatransaccion_parcial_and_more
        ]

