# Generated by Django 5.2.8 on 2025-12-14 17:57

from django.db import migrations


class _RunSQLIfMySQL(migrations.RunSQL):
    """Custom migration operation that only runs on MySQL."""

    def database_forwards(self, app_label, schema_editor, old_state, new_state):
        if schema_editor.connection.vendor == 'mysql':
            super().database_forwards(app_label, schema_editor, old_state, new_state)

    def database_backwards(self, app_label, schema_editor, old_state, new_state):
        if schema_editor.connection.vendor == 'mysql':
            super().database_backwards(app_label, schema_editor, old_state, new_state)


class Migration(migrations.Migration):
    """
    Migración para agregar CHECK constraints a nivel de base de datos.

    Estos constraints garantizan integridad de datos incluso si se insertan
    registros por fuera de Django (SQL directo, otros sistemas, etc.).

    Nota: Los constraints solo se aplican a MySQL. SQLite no soporta CHECK constraints
    en ALTER TABLE, pero Django/SQLite validan a nivel ORM.

    Cumple con CONTABILIDAD_BEST_PRACTICES.md sección 2.6
    """

    dependencies = [
        ('contabilidad', '0007_remove_empresatransaccion_parcial_and_more'),
    ]

    operations = [
        # CHECK constraints para EmpresaTransaccion (solo MySQL)
        _RunSQLIfMySQL(
            sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                ADD CONSTRAINT chk_debe_positivo
                    CHECK (debe >= 0);
            """,
            reverse_sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                DROP CONSTRAINT IF EXISTS chk_debe_positivo;
            """,
            state_operations=[],
        ),
        _RunSQLIfMySQL(
            sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                ADD CONSTRAINT chk_haber_positivo
                    CHECK (haber >= 0);
            """,
            reverse_sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                DROP CONSTRAINT IF EXISTS chk_haber_positivo;
            """,
            state_operations=[],
        ),
        _RunSQLIfMySQL(
            sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                ADD CONSTRAINT chk_no_ambos_positivos
                    CHECK (NOT (debe > 0 AND haber > 0));
            """,
            reverse_sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                DROP CONSTRAINT IF EXISTS chk_no_ambos_positivos;
            """,
            state_operations=[],
        ),
        _RunSQLIfMySQL(
            sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                ADD CONSTRAINT chk_al_menos_uno_positivo
                    CHECK (debe > 0 OR haber > 0);
            """,
            reverse_sql="""
                ALTER TABLE contabilidad_empresa_transaccion
                DROP CONSTRAINT IF EXISTS chk_al_menos_uno_positivo;
            """,
            state_operations=[],
        ),

        # NOTA: No agregar constraints para contabilidad_transaccion
        # ya que el modelo fue removido en 0007_remove_empresatransaccion_parcial_and_more
    ]
