# Generated by Django 5.2.8 on 2025-12-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_add_check_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asiento',
            options={'managed': True, 'verbose_name': 'Asiento Contable', 'verbose_name_plural': 'Asientos Contables'},
        ),
        migrations.AlterModelOptions(
            name='plandecuentas',
            options={'managed': True, 'verbose_name': 'Plan de Cuenta', 'verbose_name_plural': 'Planes de Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'managed': True, 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
    ]
