# Generated by Django 5.2.8 on 2025-12-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_fix_invalid_transactions'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_empresa_transaccion_cta_fecha 
            ON contabilidad_empresa_transaccion (cuenta_id, asiento_id);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_empresa_transaccion_cta_fecha 
            ON contabilidad_empresa_transaccion;
            """,
            state_operations=[],
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_empresa_asiento_empresa_fecha 
            ON contabilidad_empresa_asiento (empresa_id, fecha);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_empresa_asiento_empresa_fecha 
            ON contabilidad_empresa_asiento;
            """,
            state_operations=[],
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_empresa_asiento_anulado 
            ON contabilidad_empresa_asiento (anulado);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_empresa_asiento_anulado 
            ON contabilidad_empresa_asiento;
            """,
            state_operations=[],
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_empresa_plancuenta_empresa 
            ON contabilidad_empresa_plandecuentas (empresa_id, codigo);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS idx_empresa_plancuenta_empresa 
            ON contabilidad_empresa_plandecuentas;
            """,
            state_operations=[],
        ),
    ]
