# Generated by Django 5.2.8 on 2025-12-14 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Migración de limpieza sin eliminar tablas aún (se harán manualmente después)
        # Agregar campos que falten si es necesario
        migrations.RunSQL(
            sql="SELECT 1",  # Dummy SQL para no hacer nada
            reverse_sql="SELECT 1"
        ),
    ]
