# Generated by Django 5.2.8 on 2025-12-14 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_empresatercero_delete_asiento_delete_transaccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(sql='SELECT 1', reverse_sql='SELECT 1')
    ]
