# Generated by Django 5.2.8 on 2025-12-14 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_empresatercero_delete_asiento_delete_transaccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                ALTER TABLE contabilidad_empresa_transaccion
                  ADD COLUMN IF NOT EXISTS tercero_id bigint NULL;
                ALTER TABLE contabilidad_empresa_transaccion
                  DROP FOREIGN KEY IF EXISTS contabilidad_empr_trans_tercero_fk;
                ALTER TABLE contabilidad_empresa_transaccion
                  ADD CONSTRAINT contabilidad_empr_trans_tercero_fk
                  FOREIGN KEY (tercero_id) REFERENCES contabilidad_empresa_tercero(id)
                  ON DELETE SET NULL;
                ALTER TABLE contabilidad_empresa_transaccion
                  ADD INDEX IF NOT EXISTS contab_empresatransaccion_tercero_idx (tercero_id);
            ''',
            reverse_sql='''
                ALTER TABLE contabilidad_empresa_transaccion
                  DROP FOREIGN KEY IF EXISTS contabilidad_empr_trans_tercero_fk;
                ALTER TABLE contabilidad_empresa_transaccion
                  DROP COLUMN IF EXISTS tercero_id;
            '''
        )
    ]
