# Generated by Django 5.2.8 on 2025-12-14 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_empresatercero_delete_asiento_delete_transaccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # This migration previously attempted to add a FK to a table created in 0015,
    # causing MySQL errno 150 (incorrectly formed FK) in test databases.
    # It's now a no-op; the proper ForeignKey is added in 0015 via Django operations.
    operations = [
        migrations.RunSQL(sql="SELECT 1", reverse_sql="SELECT 1")
    ]
