# Generated by Django 5.2.8 on 2025-12-15 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0014_empresatercero_delete_asiento_delete_transaccion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(help_text='RUC, Cédula, DNI u otro identificador fiscal', max_length=20)),
                ('tipo', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROVEEDOR', 'Proveedor'), ('EMPLEADO', 'Empleado'), ('ACCIONISTA', 'Accionista'), ('GOBIERNO', 'Gobierno'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terceros_creados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceros', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Tercero (Empresa)',
                'verbose_name_plural': 'Terceros (Empresas)',
                'db_table': 'contabilidad_empresa_tercero',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        # Remove legacy unmanaged models from state without touching the database
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql="SELECT 1", reverse_sql="SELECT 1"),
            ],
            state_operations=[
                migrations.DeleteModel(name='Asiento'),
                migrations.DeleteModel(name='Transaccion'),
            ],
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='ip_address_anulacion',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde la que se anuló el asiento', null=True),
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='ip_address_creacion',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde la que se creó el asiento', null=True),
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='ip_address_modificacion',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP desde la que se modificó el asiento', null=True),
        ),
        migrations.AddField(
            model_name='empresaasiento',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresatransaccion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresatransaccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(sql="SELECT 1", reverse_sql="SELECT 1"),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='plandecuentas',
                    name='padre',
                    field=models.ForeignKey(blank=True, db_comment='Clave foránea recursiva para la estructura de árbol', null=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.plandecuentas'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='empresaasiento',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresatransaccion',
            name='tercero',
            field=models.ForeignKey(blank=True, help_text='Cliente, Proveedor, Empleado, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='contabilidad.empresatercero'),
        ),
        migrations.AddIndex(
            model_name='empresatercero',
            index=models.Index(fields=['empresa', 'tipo'], name='contabilida_empresa_f0fa6d_idx'),
        ),
        migrations.AddIndex(
            model_name='empresatercero',
            index=models.Index(fields=['empresa', 'activo'], name='contabilida_empresa_ff4cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='empresatercero',
            index=models.Index(fields=['numero_identificacion'], name='contabilida_numero__9a26a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='empresatercero',
            unique_together={('empresa', 'numero_identificacion')},
        ),
    ]
