# Generated by Django 5.2.8 on 2025-12-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0016_convert_int_pk_to_bigint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaasiento',
            name='numero_asiento',
            field=models.PositiveIntegerField(editable=False, help_text='Número secuencial del asiento por empresa (auditoría)'),
        ),
    ]
