# Generated by Django 5.2.8 on 2026-01-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_alter_empresaasiento_numero_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='eslogan',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/'),
        ),
    ]
