# Generated by Django 5.2.8 on 2026-01-11 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_add_logo_eslogan_to_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresaplancuenta',
            name='estado_situacion',
        ),
    ]
