# Generated by Django 5.2.8 on 2026-01-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0019_remove_estado_situacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresacomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comentario (Empresa)', 'verbose_name_plural': 'Comentarios (Empresas)'},
        ),
        migrations.AlterField(
            model_name='empresacomment',
            name='section',
            field=models.CharField(choices=[('PL', 'Plan de Cuentas'), ('DI', 'Libro Diario'), ('MA', 'Libro Mayor'), ('BC', 'Balance de Comprobación'), ('EF', 'Estados Financieros')], max_length=2),
        ),
    ]
