# Generated by Django 5.2.8 on 2026-01-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0020_alter_empresacomment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plandecuentas',
            options={'managed': False, 'verbose_name': 'Plan de Cuenta', 'verbose_name_plural': 'Planes de Cuentas'},
        ),
    ]
