# Generated by Django 5.2.8 on 2026-01-11 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_alter_plandecuentas_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomaliaDetectada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_id', models.BigIntegerField(blank=True, help_text='ID del asiento anómalo', null=True)),
                ('transaccion_id', models.BigIntegerField(blank=True, help_text='ID de la transacción anómala', null=True)),
                ('tipo_anomalia', models.CharField(choices=[('MONTO', 'Monto Inusual'), ('FREQ', 'Frecuencia Anormal'), ('PTRN', 'Patrón Sospechoso'), ('CONT', 'Inconsistencia Contable'), ('TEMP', 'Temporal Atípica')], max_length=5)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=7)),
                ('score_anomalia', models.DecimalField(decimal_places=6, help_text='Score del algoritmo (ej: -0.5 en Isolation Forest)', max_digits=10)),
                ('descripcion', models.TextField(help_text='Explicación de por qué es anómala')),
                ('algoritmo_usado', models.CharField(default='IsolationForest', max_length=100)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('revisada', models.BooleanField(default=False)),
                ('es_falso_positivo', models.BooleanField(default=False)),
                ('notas_revision', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='contabilidad.empresa')),
                ('revisada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anomalía Detectada',
                'verbose_name_plural': 'Anomalías Detectadas',
                'db_table': 'contabilidad_anomalia_detectada',
                'ordering': ['-fecha_deteccion', '-severidad'],
                'indexes': [models.Index(fields=['empresa', '-fecha_deteccion'], name='contabilida_empresa_f17c57_idx'), models.Index(fields=['severidad', 'revisada'], name='contabilida_severid_96b283_idx'), models.Index(fields=['tipo_anomalia'], name='contabilida_tipo_an_75549d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaCuentaEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_json', models.JSONField(help_text='Representación vectorial de la cuenta (768 dimensiones)')),
                ('modelo_usado', models.CharField(default='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2', max_length=100)),
                ('dimension', models.IntegerField(default=768)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('texto_fuente', models.TextField(help_text='Código + Descripción + Tipo usado para generar embedding')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='contabilidad.empresaplancuenta')),
            ],
            options={
                'verbose_name': 'Embedding de Cuenta',
                'verbose_name_plural': 'Embeddings de Cuentas',
                'db_table': 'contabilidad_cuenta_embedding',
                'indexes': [models.Index(fields=['cuenta'], name='contabilida_cuenta__2e240c_idx'), models.Index(fields=['-fecha_generacion'], name='contabilida_fecha_g_77019c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmpresaMetrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('activo_corriente', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pasivo_corriente', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('razon_corriente', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('prueba_acida', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ingresos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('gastos_totales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('utilidad_neta', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('margen_neto', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, help_text='Return on Equity', max_digits=10, null=True)),
                ('roa', models.DecimalField(blank=True, decimal_places=4, help_text='Return on Assets', max_digits=10, null=True)),
                ('total_activos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_pasivos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_patrimonio', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('razon_endeudamiento', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('num_transacciones', models.IntegerField(default=0)),
                ('num_cuentas_activas', models.IntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Métrica Empresarial',
                'verbose_name_plural': 'Métricas Empresariales',
                'db_table': 'contabilidad_empresa_metrica',
                'ordering': ['-fecha_calculo'],
                'indexes': [models.Index(fields=['empresa', '-fecha_calculo'], name='contabilida_empresa_36a83d_idx'), models.Index(fields=['periodo_inicio', 'periodo_fin'], name='contabilida_periodo_6b6bdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrediccionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prediccion', models.CharField(choices=[('INGR', 'Ingresos'), ('GAST', 'Gastos'), ('FLUJ', 'Flujo de Efectivo'), ('PATR', 'Patrimonio'), ('UTIL', 'Utilidad')], max_length=4)),
                ('modelo_usado', models.CharField(choices=[('PROPHET', 'Facebook Prophet'), ('ARIMA', 'ARIMA'), ('LINEAR', 'Regresión Lineal'), ('RF', 'Random Forest')], max_length=10)),
                ('fecha_prediccion', models.DateField(help_text='Fecha para la cual se hace la predicción')),
                ('valor_predicho', models.DecimalField(decimal_places=2, max_digits=20)),
                ('limite_inferior', models.DecimalField(blank=True, decimal_places=2, help_text='Intervalo de confianza inferior', max_digits=20, null=True)),
                ('limite_superior', models.DecimalField(blank=True, decimal_places=2, help_text='Intervalo de confianza superior', max_digits=20, null=True)),
                ('confianza', models.DecimalField(decimal_places=2, default=95.0, help_text='Nivel de confianza en %', max_digits=5)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('metricas_modelo', models.JSONField(blank=True, help_text='MAE, RMSE, R², etc.', null=True)),
                ('datos_entrenamiento', models.JSONField(blank=True, help_text='Referencia a datos usados', null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Predicción Financiera',
                'verbose_name_plural': 'Predicciones Financieras',
                'db_table': 'contabilidad_prediccion_financiera',
                'ordering': ['fecha_prediccion'],
                'indexes': [models.Index(fields=['empresa', 'tipo_prediccion', 'fecha_prediccion'], name='contabilida_empresa_32eb9e_idx'), models.Index(fields=['-fecha_generacion'], name='contabilida_fecha_g_b79ade_idx')],
            },
        ),
    ]
