# Generated by Django 5.2.8 on 2026-01-17 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0022_anomaliadetectada_empresacuentaembedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, help_text='Código único del producto (SKU)', max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, help_text='Categoría del producto (ej: Electrónica, Alimentos, etc.)', max_length=100)),
                ('unidad_medida', models.CharField(help_text='Unidad de medida (unid, kg, litros, cajas, etc.)', max_length=20)),
                ('metodo_valoracion', models.CharField(choices=[('PEPS', 'PEPS (Primero en Entrar, Primero en Salir / FIFO)'), ('UEPS', 'UEPS (Último en Entrar, Primero en Salir / LIFO)'), ('PROMEDIO', 'Promedio Ponderado')], default='PROMEDIO', help_text='Método para calcular el costo de las salidas', max_length=20)),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Stock mínimo (alerta de reabastecimiento)', max_digits=15)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=3, help_text='Stock máximo (opcional)', max_digits=15, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si es False, el producto está descontinuado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('cuenta_costo_venta', models.ForeignKey(blank=True, help_text='Cuenta de Costo de Ventas (tipo Costo, ej: 5.1)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_costo', to='contabilidad.empresaplancuenta')),
                ('cuenta_inventario', models.ForeignKey(help_text='Cuenta contable de inventario (debe ser tipo Activo, ej: 1.1.04)', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='contabilidad.empresaplancuenta')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_inventario', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Producto (Inventario)',
                'verbose_name_plural': 'Productos (Inventario)',
                'db_table': 'contabilidad_producto_inventario',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoKardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (Compra)'), ('SALIDA', 'Salida (Venta/Consumo)'), ('AJUSTE_ENTRADA', 'Ajuste Positivo (Inventario encontrado)'), ('AJUSTE_SALIDA', 'Ajuste Negativo (Merma/Robo)'), ('DEVOLUCION_COMPRA', 'Devolución de Compra'), ('DEVOLUCION_VENTA', 'Devolución de Venta')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=3, help_text='Cantidad de unidades (positivo para entradas, valor absoluto para salidas)', max_digits=15)),
                ('costo_unitario', models.DecimalField(decimal_places=6, help_text='Costo unitario del movimiento (para entradas) o costo asignado (para salidas)', max_digits=15)),
                ('valor_total_movimiento', models.DecimalField(decimal_places=2, help_text='Valor total del movimiento (cantidad * costo_unitario)', max_digits=20)),
                ('cantidad_saldo', models.DecimalField(decimal_places=3, help_text='Stock resultante después del movimiento', max_digits=15)),
                ('costo_promedio', models.DecimalField(decimal_places=6, help_text='Costo promedio ponderado después del movimiento', max_digits=15)),
                ('valor_total_saldo', models.DecimalField(decimal_places=2, help_text='Valor total del inventario después del movimiento (cantidad_saldo * costo_promedio)', max_digits=20)),
                ('documento_referencia', models.CharField(blank=True, help_text='Número de factura, orden de compra, etc.', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.ForeignKey(blank=True, help_text='Asiento contable asociado a este movimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_kardex', to='contabilidad.empresaasiento')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tercero', models.ForeignKey(blank=True, help_text='Proveedor (entrada) o cliente (salida)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.empresatercero')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.productoinventario')),
            ],
            options={
                'verbose_name': 'Movimiento Kardex',
                'verbose_name_plural': 'Movimientos Kardex',
                'db_table': 'contabilidad_movimiento_kardex',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaCierrePeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(help_text='Año fiscal cerrado (ej: 2025, 2026)')),
                ('fecha_cierre', models.DateField(help_text='Fecha en la que se ejecutó el cierre (último día del ejercicio)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Timestamp de cuando se registró el cierre en el sistema')),
                ('utilidad_neta', models.DecimalField(decimal_places=2, default=0, help_text='Utilidad o pérdida del ejercicio (Ingresos - Costos - Gastos)', max_digits=20)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_costos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('bloqueado', models.BooleanField(default=True, help_text='Si es True, no se permiten crear/editar asientos en este periodo')),
                ('notas', models.TextField(blank=True, help_text='Observaciones sobre el cierre (opcional)')),
                ('asiento_cierre', models.ForeignKey(blank=True, help_text='Asiento contable que registra el cierre del periodo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierre_generado', to='contabilidad.empresaasiento')),
                ('cerrado_por', models.ForeignKey(help_text='Usuario que ejecutó el cierre', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_periodo', to='contabilidad.empresa')),
            ],
            options={
                'verbose_name': 'Cierre de Periodo',
                'verbose_name_plural': 'Cierres de Periodos',
                'db_table': 'contabilidad_empresa_cierre_periodo',
                'ordering': ['-periodo'],
                'indexes': [models.Index(fields=['empresa', '-periodo'], name='contabilida_empresa_6401b2_idx'), models.Index(fields=['fecha_cierre'], name='contabilida_fecha_c_c6249c_idx')],
                'unique_together': {('empresa', 'periodo')},
            },
        ),
        migrations.AddIndex(
            model_name='productoinventario',
            index=models.Index(fields=['empresa', 'sku'], name='contabilida_empresa_427581_idx'),
        ),
        migrations.AddIndex(
            model_name='productoinventario',
            index=models.Index(fields=['empresa', 'activo'], name='contabilida_empresa_13ba21_idx'),
        ),
        migrations.AddIndex(
            model_name='productoinventario',
            index=models.Index(fields=['categoria'], name='contabilida_categor_c84a8d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productoinventario',
            unique_together={('empresa', 'sku')},
        ),
        migrations.AddIndex(
            model_name='movimientokardex',
            index=models.Index(fields=['producto', 'fecha'], name='contabilida_product_b18301_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientokardex',
            index=models.Index(fields=['producto', '-fecha', '-id'], name='contabilida_product_991e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientokardex',
            index=models.Index(fields=['tipo_movimiento'], name='contabilida_tipo_mo_1c74b9_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientokardex',
            index=models.Index(fields=['fecha'], name='contabilida_fecha_10fea5_idx'),
        ),
    ]
