# Generated by Django 5.2.8 on 2026-01-17 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0023_kardex_cierre_system'),
    ]

    operations = [
        # 1. Crear tabla de cache de métricas
        migrations.CreateModel(
            name='EmpresaMetricasCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del período (YYYY-MM-01)')),
                ('metricas_json', models.JSONField(help_text='Métricas pre-calculadas en formato JSON')),
                ('fecha_calculo', models.DateTimeField(auto_now=True, help_text='Última actualización')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_cache', to='contabilidad.empresa')),
            ],
            options={
                'db_table': 'contabilidad_empresa_metricas_cache',
                'verbose_name': 'Cache de Métricas',
                'verbose_name_plural': 'Cache de Métricas',
                'indexes': [
                    models.Index(fields=['empresa', '-fecha_calculo'], name='cont_emp_metr_cache_idx'),
                    models.Index(fields=['empresa', 'periodo'], name='cont_emp_periodo_idx'),
                ],
                'unique_together': {('empresa', 'periodo')},
            },
        ),

        # 2. Agregar índice FULLTEXT a descripciones de cuentas (MariaDB)
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE contabilidad_empresa_plandecuentas
                ADD FULLTEXT INDEX idx_ft_descripcion_codigo (descripcion, codigo)
                """,
            ],
            reverse_sql=[
                "ALTER TABLE contabilidad_empresa_plandecuentas DROP INDEX idx_ft_descripcion_codigo",
            ],
        ),

        # 3. Crear trigger para invalidar cache al insertar asientos
        migrations.RunSQL(
            sql=[
                """
                CREATE TRIGGER trg_invalidar_metricas_cache_insert
                AFTER INSERT ON contabilidad_empresa_asiento
                FOR EACH ROW
                BEGIN
                    DELETE FROM contabilidad_empresa_metricas_cache
                    WHERE empresa_id = NEW.empresa_id
                      AND periodo = DATE_FORMAT(NEW.fecha, '%Y-%m-01');
                END
                """,
            ],
            reverse_sql=[
                "DROP TRIGGER IF EXISTS trg_invalidar_metricas_cache_insert",
            ],
        ),

        # 4. Crear trigger para invalidar cache al actualizar asientos
        migrations.RunSQL(
            sql=[
                """
                CREATE TRIGGER trg_invalidar_metricas_cache_update
                AFTER UPDATE ON contabilidad_empresa_asiento
                FOR EACH ROW
                BEGIN
                    DELETE FROM contabilidad_empresa_metricas_cache
                    WHERE empresa_id = NEW.empresa_id
                      AND periodo IN (
                          DATE_FORMAT(NEW.fecha, '%Y-%m-01'),
                          DATE_FORMAT(OLD.fecha, '%Y-%m-01')
                      );
                END
                """,
            ],
            reverse_sql=[
                "DROP TRIGGER IF EXISTS trg_invalidar_metricas_cache_update",
            ],
        ),

        # 5. Crear trigger para invalidar cache al eliminar asientos
        migrations.RunSQL(
            sql=[
                """
                CREATE TRIGGER trg_invalidar_metricas_cache_delete
                AFTER DELETE ON contabilidad_empresa_asiento
                FOR EACH ROW
                BEGIN
                    DELETE FROM contabilidad_empresa_metricas_cache
                    WHERE empresa_id = OLD.empresa_id
                      AND periodo = DATE_FORMAT(OLD.fecha, '%Y-%m-01');
                END
                """,
            ],
            reverse_sql=[
                "DROP TRIGGER IF EXISTS trg_invalidar_metricas_cache_delete",
            ],
        ),
    ]
