# Generated by Django 5.2.8 on 2026-01-17 21:31

from django.db import migrations


def convert_all_user_fks_to_bigint(apps, schema_editor):
    """
    Convierte TODAS las columnas FK que apuntan a auth_user de integer a bigint.
    Se ejecuta DESPUÉS de que todas las apps hayan creado sus tablas iniciales.

    Nota: Los FKs fueron creados sin constraints (db_constraint=False) en las migraciones,
    así que solo necesitamos convertir los tipos de columna a bigint y agregar constraints nuevas.
    """
    with schema_editor.connection.cursor() as cursor:
        db_name = schema_editor.connection.settings_dict['NAME']

        # Get ALL columnas que referencian auth_user (incluso sin constraint)
        cursor.execute("""
            SELECT TABLE_NAME, COLUMN_NAME
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = %s
            AND TABLE_NAME NOT IN ('auth_user', 'auth_group', 'auth_permission', 'django_content_type', 'django_admin_log', 'authtoken_token')
            AND COLUMN_NAME IN ('owner_id', 'creado_por_id', 'author_id', 'docente_id', 'user_id', 'actor_id', 'target_user_id', 'creator_id', 'recipient_id', 'student_id', 'cerrado_por_id', 'revisada_por_id', 'modificado_por_id')
            AND COLUMN_TYPE = 'int(11)'
        """, [db_name])

        fks_to_convert = cursor.fetchall()

        # Convertir todos los campos a bigint
        for table, column in fks_to_convert:
            # Check if column is nullable
            cursor.execute("""
                SELECT IS_NULLABLE
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = %s
                AND TABLE_NAME = %s
                AND COLUMN_NAME = %s
            """, [db_name, table, column])

            result = cursor.fetchone()
            if result:
                is_nullable = result[0] == 'YES'
                null_clause = 'NULL' if is_nullable else 'NOT NULL'
                try:
                    cursor.execute(f"ALTER TABLE `{table}` MODIFY `{column}` bigint {null_clause}")
                except Exception as e:
                    # Skip si ya fue convertido
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0022_alter_empresacomment_section_and_more'),
        ('core', '0010_notification_empresa_fk'),
    ]

    operations = [
        migrations.RunPython(convert_all_user_fks_to_bigint, reverse_code=migrations.RunPython.noop),
    ]
